version: '3.7'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLROOTPASSWORD
      - MYSQL_PASSWORD=$MYSQLPASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      nextcloud_net:
        ipv4_address: 172.100.0.11  

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      nextcloud_net:
        ipv4_address: 172.100.0.14

  app:
    image: nextcloud:fpm-alpine
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - MYSQL_PASSWORD=$MYSQLPASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    depends_on:
      - db
      - redis
    networks:
      nextcloud_net:
        ipv4_address: 172.100.0.12

  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 7778:80
    volumes:
      - nextcloud:/var/www/html:ro
      - /opt/nuevo/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      nextcloud_net:
        ipv4_address: 172.100.0.10
        
  cron:
    image: nextcloud:fpm-alpine
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      nextcloud_net:
        ipv4_address: 172.100.0.13
        
volumes:
  db:
  nextcloud:

networks:
  nextcloud_net:
    ipam:
      config:
        - subnet: 172.100.0.0/16
